table Account

	column AccountID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: AccountID

	column AccountNumber
		dataType: int64
		summarizeBy: none
		sourceColumn: AccountNumber

	column AccountName
		dataType: string
		summarizeBy: none
		sourceColumn: AccountName

	column AccountType
		dataType: string
		summarizeBy: none
		sourceColumn: AccountType

	column AccountSubType
		dataType: string
		summarizeBy: none
		sourceColumn: AccountSubType

	column NormalBalance
		dataType: string
		summarizeBy: none
		sourceColumn: NormalBalance

	partition Account = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T1_Account",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"AccountID", "AccountNumber", "AccountName", "AccountType", "AccountSubType", "NormalBalance"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"AccountID", Int64.Type}, {"AccountNumber", Int64.Type}, {"AccountName", type text},
			        {"AccountType", type text}, {"AccountSubType", type text}, {"NormalBalance", type text}})
			in
			    Typed

