table BudgetLine

	measure 'Gross to Net' =
			SWITCH (
			    SELECTEDVALUE ( Steps[Step] ),
			    "At list price", [List Amount],
			    "Price lists and overrides", [Price Before Discount] - [List Amount],
			    "Promotions", [Revenue] - [Price Before Discount],
			    [Revenue]
			)
		formatString: #,0.00

	measure Budget = SUM ( BudgetLine[BudgetAmount] )
		formatString: #,0.00

	measure Actual = [GL Amount]
		formatString: #,0.00

	measure Variance = [Actual] - [Budget]
		formatString: #,0.00

	measure 'Variance %' = DIVIDE ( [Variance], [Budget] )
		formatString: 0.0%

	measure 'Flexed Budget' =
			VAR CommissionBudget =
			    CALCULATE ( [Budget], KEEPFILTERS ( Account[AccountNumber] = 6290 ) )
			VAR CommissionRate =
			    DIVIDE (
			        CALCULATE ( [Budget], REMOVEFILTERS ( Account ), REMOVEFILTERS ( CostCenter ),
			            Account[AccountNumber] = 6290 ),
			        CALCULATE ( [Budget], REMOVEFILTERS ( Account ), REMOVEFILTERS ( CostCenter ),
			            Account[AccountNumber] IN { 4010, 4020, 4030, 4040 } )
			    )
			VAR ProductRevenue =
			    CALCULATE ( [Revenue], 'Item'[ItemGroup] <> "Services" )
			RETURN
			    [Budget] - CommissionBudget
			        + IF ( NOT ISBLANK ( CommissionBudget ), CommissionRate * ProductRevenue )
		formatString: #,0.00

	measure 'Volume Effect' = [Flexed Budget] - [Budget]
		formatString: #,0.00

	measure 'Classification Effect' = CALCULATE ( [Actual] - [Budget], KEEPFILTERS ( Account[AccountNumber] = 6130 ) )
		formatString: #,0.00

	measure 'Remaining Variance' = [Variance] - [Volume Effect] - [Classification Effect]
		formatString: #,0.00

	measure 'Remaining %' = DIVIDE ( [Remaining Variance], [Flexed Budget] )
		formatString: 0.0%

	column BudgetLineID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: BudgetLineID

	column FiscalYear
		dataType: int64
		summarizeBy: none
		sourceColumn: FiscalYear

	column Month
		dataType: int64
		summarizeBy: none
		sourceColumn: Month

	column AccountID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: AccountID

	column CostCenterID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: CostCenterID

	column ItemID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ItemID

	column BudgetAmount
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: BudgetAmount

	column BudgetCategory
		dataType: string
		summarizeBy: none
		sourceColumn: BudgetCategory

	column DriverType
		dataType: string
		summarizeBy: none
		sourceColumn: DriverType

	column BudgetDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: BudgetDate

	partition BudgetLine = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T77_BudgetLine",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"BudgetLineID", "FiscalYear", "Month", "AccountID", "CostCenterID", "ItemID",
			        "BudgetAmount", "BudgetCategory", "DriverType"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"BudgetLineID", Int64.Type}, {"FiscalYear", Int64.Type},
			        {"Month", Int64.Type}, {"AccountID", Int64.Type}, {"CostCenterID", Int64.Type}, {"ItemID", Int64.Type},
			        {"BudgetAmount", type number}, {"BudgetCategory", type text}, {"DriverType", type text}}),
			    PandL = Table.SelectRows(Typed, each [BudgetCategory] <> "Balance Sheet"),
			    Dated = Table.AddColumn(PandL, "BudgetDate", each #date([FiscalYear], [Month], 1), type date)
			in
			    Dated

