project:
  type: book
  pre-render:
    - python scripts/export_drawio_svgs.py

book:
  title: "Accounting Analytics"
  author: "Mauricio Codesso"
  date: "3/30/2026"
  chapters:
    - index.md
    - 00_preface.md
    - 00_to_the_student.md
    - 00_about_the_dataset.md
    - downloads.md
    - part: "Part I: Foundations of Accounting Analytics"
      chapters:
        - 01_chapter.md
        - 02_chapter.md
        - 03_chapter.md
    - part: "Part II: Accounting Analytics with Excel"
    - part: "Part III: Accounting Analytics with SQL"
    - part: "Part IV: Data Visualization and Power BI"
    - part: "Part V: Integrated and Applied Topics"


format:
  html:
    theme:
      - cosmo
      - styles/book.scss
    toc: true
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    link-external-newwindow: true
    number-sections: true
  pdf:
    documentclass: scrreprt
    include-in-header: styles/book-pdf.tex
    colorlinks: true
    fig-cap-location: bottom
    tbl-cap-location: top
  docx:
    reference-doc: styles/reference.docx

crossref:
  fig-title: Figure
  tbl-title: Table
