{{< pagebreak >}}

## References

AACSB International. (2026). *2026 standards for accounting accreditation*. <https://www.aacsb.edu/-/media/documents/accreditation/2026/2026-accounting-standards.pdf>

American Institute of Certified Public Accountants & National Association of State Boards of Accountancy. (2021). *CPA Evolution model curriculum*. <https://www.thiswaytocpa.com/collectedmedia/files/cpa-evolution-model-curriculum-update.pdf>

Institute of Management Accountants. (2025). *IMA expanded management accounting competency framework: Advancing competencies for the 21st-century management accountant*. <https://mc-69e30ef4-758e-4371-ac6f-2657-cdn-endpoint.azureedge.net/-/media/IMA/Files/Home/Career-Resources/Competency-Framework/Competency-Framework-White-Paper.ashx>

International Federation of Accountants. (2025a). *International Education Standard (IES) 2: Initial professional development—Technical competence (2026)*. <https://education.ifac.org/part/ies-2>

International Federation of Accountants. (2025b). *International Education Standard (IES) 3: Initial professional development—Professional skills (2026)*. <https://education.ifac.org/part/ies-3>

International Federation of Accountants. (2025c). *International Education Standard (IES) 4: Initial professional development—Professional values, ethics, and attitudes (2026)*. <https://education.ifac.org/part/ies-4>
