"""Public Chapter 12 tutorial SQL shared by book figures and slides.

These definitions never open a database. Run authoring examples against a
read-only connection; save views only in a separate student working copy.
"""

HEADER = (
    "/* Audit.sql: tests of the records behind the manufacturing variance\n"
    "   Database: CharlesRiver_Work.sqlite (a copy of CharlesRiver.sqlite)\n"
    "   Prepared by: your name, date; reviewed by: name, date\n"
    "   Checks: populations tie to the ledger; exceptions listed by test */"
)

_APPROVAL_CTE = (
    "WITH ApprovalExceptions AS (\n"
    "    SELECT 'Self-approved' AS Test, po.PONumber, po.OrderTotal\n"
    "    FROM PurchaseOrder AS po\n"
    "    WHERE po.CreatedByEmployeeID = po.ApprovedByEmployeeID\n"
    "    UNION ALL\n"
    "    SELECT 'Above approver limit', po.PONumber, po.OrderTotal\n"
    "    FROM PurchaseOrder AS po\n"
    "        INNER JOIN Employee AS e\n"
    "            ON e.EmployeeID = po.ApprovedByEmployeeID\n"
    "    WHERE po.OrderTotal > e.MaxApprovalAmount\n"
    "    UNION ALL\n"
    "    SELECT 'Approved after termination', po.PONumber, po.OrderTotal\n"
    "    FROM PurchaseOrder AS po\n"
    "        INNER JOIN Employee AS e\n"
    "            ON e.EmployeeID = po.ApprovedByEmployeeID\n"
    "    WHERE e.TerminationDate IS NOT NULL\n"
    "        AND po.OrderDate > e.TerminationDate\n"
    ")")

_PLANT_DAYS = ("    FROM TimeClockEntry AS tc\n"
               "        INNER JOIN Employee AS e ON e.EmployeeID = tc.EmployeeID\n"
               "        INNER JOIN CostCenter AS cc ON cc.CostCenterID = e.CostCenterID\n"
               "    WHERE cc.CostCenterName = 'Manufacturing'\n"
               "    GROUP BY tc.WorkDate\n")

_EARNINGS = ("FROM PayrollRegisterLine AS prl\n"
             "    INNER JOIN PayrollRegister AS pr\n"
             "        ON pr.PayrollRegisterID = prl.PayrollRegisterID\n"
             "    INNER JOIN LaborTimeEntry AS lt\n"
             "        ON lt.LaborTimeEntryID = prl.LaborTimeEntryID\n"
             "    INNER JOIN Employee AS pe ON pe.EmployeeID = pr.EmployeeID\n"
             "    INNER JOIN Employee AS we ON we.EmployeeID = lt.EmployeeID\n")

_AFTER_END = ("CASE WHEN lt.WorkDate > op.ActualEndDate\n"
              "        THEN lt.RegularHours + lt.OvertimeHours ELSE 0 END")

QUERIES = [
    # Tutorial 12.1: the ledger
    ("je_population",
     "-- Tutorial 12.1, test L1: journal entries against the ledger\n"
     "-- Population: all journal entries; expected: counts and totals agree",
     "SELECT\n"
     "    (SELECT COUNT(*) FROM JournalEntry) AS Entries,\n"
     "    (SELECT ROUND(SUM(TotalAmount), 2) FROM JournalEntry) AS EntryTotal,\n"
     "    (SELECT COUNT(DISTINCT SourceDocumentID) FROM GLEntry\n"
     "        WHERE SourceDocumentType = 'JournalEntry') AS PostedEntries,\n"
     "    (SELECT ROUND(SUM(Debit), 2) FROM GLEntry\n"
     "        WHERE SourceDocumentType = 'JournalEntry') AS PostedDebits;"),
    ("payroll_population",
     "-- Tutorial 12.1, test L2: manufacturing payroll against the ledger\n"
     "-- Population: Manufacturing registers; expected: no difference",
     "SELECT reg.FiscalYear, reg.RegisterCost, gl.LedgerCost,\n"
     "    ROUND(reg.RegisterCost - gl.LedgerCost, 2) AS Difference\n"
     "FROM (\n"
     "    SELECT pp.FiscalYear,\n"
     "        ROUND(SUM(pr.GrossPay + pr.EmployerPayrollTax\n"
     "            + pr.EmployerBenefits), 2) AS RegisterCost\n"
     "    FROM PayrollRegister AS pr\n"
     "        INNER JOIN PayrollPeriod AS pp\n"
     "            ON pp.PayrollPeriodID = pr.PayrollPeriodID\n"
     "        INNER JOIN CostCenter AS cc ON cc.CostCenterID = pr.CostCenterID\n"
     "    WHERE cc.CostCenterName = 'Manufacturing'\n"
     "    GROUP BY pp.FiscalYear\n"
     ") AS reg\n"
     "    INNER JOIN (\n"
     "        SELECT gl.FiscalYear, ROUND(SUM(gl.Debit), 2) AS LedgerCost\n"
     "        FROM GLEntry AS gl\n"
     "            INNER JOIN CostCenter AS cc\n"
     "                ON cc.CostCenterID = gl.CostCenterID\n"
     "        WHERE gl.SourceDocumentType = 'PayrollSummary'\n"
     "            AND cc.CostCenterName = 'Manufacturing'\n"
     "        GROUP BY gl.FiscalYear\n"
     "    ) AS gl ON gl.FiscalYear = reg.FiscalYear\n"
     "ORDER BY reg.FiscalYear;"),
    ("trace",
     "-- Tutorial 12.1, test L3: postings and documents traced both ways\n"
     "-- Population: four document types; expected: no rows",
     "SELECT 'Posting with no payroll payment' AS Test,\n"
     "    gl.GLEntryID AS RecordID, gl.PostingDate AS RecordDate,\n"
     "    gl.Debit + gl.Credit AS Amount\n"
     "FROM GLEntry AS gl\n"
     "    LEFT JOIN PayrollPayment AS pp\n"
     "        ON pp.PayrollPaymentID = gl.SourceDocumentID\n"
     "WHERE gl.SourceDocumentType = 'PayrollPayment'\n"
     "    AND pp.PayrollPaymentID IS NULL\n"
     "UNION ALL\n"
     "SELECT 'Posting with no supplier payment', gl.GLEntryID,\n"
     "    gl.PostingDate, gl.Debit + gl.Credit\n"
     "FROM GLEntry AS gl\n"
     "    LEFT JOIN DisbursementPayment AS dp\n"
     "        ON dp.DisbursementID = gl.SourceDocumentID\n"
     "WHERE gl.SourceDocumentType = 'DisbursementPayment'\n"
     "    AND dp.DisbursementID IS NULL\n"
     "UNION ALL\n"
     "SELECT 'Sales invoice never posted', si.SalesInvoiceID,\n"
     "    si.InvoiceDate, si.GrandTotal\n"
     "FROM SalesInvoice AS si\n"
     "    LEFT JOIN GLEntry AS gl ON gl.SourceDocumentType = 'SalesInvoice'\n"
     "        AND gl.SourceDocumentID = si.SalesInvoiceID\n"
     "WHERE gl.GLEntryID IS NULL\n"
     "UNION ALL\n"
     "SELECT 'Supplier invoice never posted', pi.PurchaseInvoiceID,\n"
     "    pi.InvoiceDate, pi.GrandTotal\n"
     "FROM PurchaseInvoice AS pi\n"
     "    LEFT JOIN GLEntry AS gl ON gl.SourceDocumentType = 'PurchaseInvoice'\n"
     "        AND gl.SourceDocumentID = pi.PurchaseInvoiceID\n"
     "WHERE gl.GLEntryID IS NULL;"),
    ("unpaid_registers",
     "-- Tutorial 12.1, test L4: approved registers with no payment\n"
     "-- Population: all payroll registers; expected: no rows",
     "SELECT pr.PayrollRegisterID, e.JobTitle,\n"
     "    ec.CostCenterName AS EmployeeCenter,\n"
     "    rc.CostCenterName AS RegisterCenter, e.TerminationDate,\n"
     "    pp.PayDate, pr.GrossPay, pr.NetPay, pr.Status\n"
     "FROM PayrollRegister AS pr\n"
     "    INNER JOIN PayrollPeriod AS pp\n"
     "        ON pp.PayrollPeriodID = pr.PayrollPeriodID\n"
     "    INNER JOIN Employee AS e ON e.EmployeeID = pr.EmployeeID\n"
     "    INNER JOIN CostCenter AS ec ON ec.CostCenterID = e.CostCenterID\n"
     "    INNER JOIN CostCenter AS rc ON rc.CostCenterID = pr.CostCenterID\n"
     "    LEFT JOIN PayrollPayment AS pay\n"
     "        ON pay.PayrollRegisterID = pr.PayrollRegisterID\n"
     "WHERE pay.PayrollPaymentID IS NULL;"),
    ("revenue_cutoff",
     "-- Tutorial 12.1, test L5: revenue posted in the year of delivery\n"
     "-- Population: all sales invoices; expected: no rows",
     "WITH Shipped AS (\n"
     "    SELECT sil.SalesInvoiceID, MIN(s.ShipmentDate) AS ShipmentDate,\n"
     "        MAX(s.DeliveryDate) AS DeliveryDate\n"
     "    FROM SalesInvoiceLine AS sil\n"
     "        INNER JOIN ShipmentLine AS sl\n"
     "            ON sl.ShipmentLineID = sil.ShipmentLineID\n"
     "        INNER JOIN Shipment AS s ON s.ShipmentID = sl.ShipmentID\n"
     "    GROUP BY sil.SalesInvoiceID\n"
     "),\n"
     "Posted AS (\n"
     "    SELECT SourceDocumentID AS SalesInvoiceID,\n"
     "        MIN(PostingDate) AS PostingDate\n"
     "    FROM GLEntry\n"
     "    WHERE SourceDocumentType = 'SalesInvoice'\n"
     "    GROUP BY SourceDocumentID\n"
     "),\n"
     "Classified AS (\n"
     "    SELECT si.SubTotal,\n"
     "        strftime('%Y', sh.DeliveryDate) AS DeliveryYear,\n"
     "        CASE\n"
     "            WHEN strftime('%Y', p.PostingDate)\n"
     "                    <> strftime('%Y', sh.DeliveryDate)\n"
     "                THEN 'Revenue posted in another year'\n"
     "            WHEN si.InvoiceDate < sh.ShipmentDate\n"
     "                THEN 'Invoice dated before shipment'\n"
     "            ELSE 'In the year of delivery'\n"
     "        END AS Finding\n"
     "    FROM SalesInvoice AS si\n"
     "        INNER JOIN Shipped AS sh\n"
     "            ON sh.SalesInvoiceID = si.SalesInvoiceID\n"
     "        INNER JOIN Posted AS p ON p.SalesInvoiceID = si.SalesInvoiceID\n"
     ")\n"
     "SELECT Finding, DeliveryYear, COUNT(*) AS Invoices,\n"
     "    ROUND(SUM(SubTotal), 2) AS SubTotal\n"
     "FROM Classified\n"
     "WHERE Finding <> 'In the year of delivery'\n"
     "GROUP BY Finding, DeliveryYear\n"
     "ORDER BY Finding, DeliveryYear;"),
    ("unbilled_shipments",
     "-- Tutorial 12.1, test L6: shipments never invoiced\n"
     "-- Population: all shipment lines; expected: no rows",
     "SELECT s.ShipmentNumber, s.ShipmentDate, s.DeliveryDate,\n"
     "    ROUND(sl.ExtendedStandardCost, 2) AS StandardCost,\n"
     "    ROUND(sl.QuantityShipped * sol.UnitPrice * (1 - sol.Discount), 2)\n"
     "        AS SalesValue\n"
     "FROM ShipmentLine AS sl\n"
     "    INNER JOIN Shipment AS s ON s.ShipmentID = sl.ShipmentID\n"
     "    INNER JOIN SalesOrderLine AS sol\n"
     "        ON sol.SalesOrderLineID = sl.SalesOrderLineID\n"
     "    LEFT JOIN SalesInvoiceLine AS sil\n"
     "        ON sil.ShipmentLineID = sl.ShipmentLineID\n"
     "WHERE sil.SalesInvoiceLineID IS NULL\n"
     "ORDER BY s.ShipmentDate;"),
    ("payroll_cutoff",
     "-- Tutorial 12.1, test L7: pay periods that cross a year-end\n"
     "-- Population: all pay periods; expected: every period processed",
     "SELECT pp.PeriodNumber, pp.PeriodStartDate, pp.PeriodEndDate,\n"
     "    pp.PayDate, pp.Status, COALESCE(reg.Registers, 0) AS Registers,\n"
     "    reg.PayrollCost\n"
     "FROM PayrollPeriod AS pp\n"
     "    LEFT JOIN (\n"
     "        SELECT PayrollPeriodID, COUNT(*) AS Registers,\n"
     "            ROUND(SUM(GrossPay + EmployerPayrollTax\n"
     "                + EmployerBenefits), 2) AS PayrollCost\n"
     "        FROM PayrollRegister\n"
     "        GROUP BY PayrollPeriodID\n"
     "    ) AS reg ON reg.PayrollPeriodID = pp.PayrollPeriodID\n"
     "WHERE strftime('%Y', pp.PeriodStartDate) <> strftime('%Y', pp.PayDate)\n"
     "ORDER BY pp.PeriodStartDate;"),
    ("accrued_payroll",
     "-- Tutorial 12.1, test L8: accrued payroll at the year-end\n"
     "-- Population: account 2030 to 2026-12-31; expected: unpaid wages",
     "SELECT gl.SourceDocumentType, COUNT(*) AS Postings,\n"
     "    ROUND(SUM(gl.Credit) - SUM(gl.Debit), 2) AS Balance\n"
     "FROM GLEntry AS gl\n"
     "    INNER JOIN Account AS a ON a.AccountID = gl.AccountID\n"
     "WHERE a.AccountNumber = 2030 AND gl.PostingDate <= '2026-12-31'\n"
     "GROUP BY gl.SourceDocumentType;"),
    # Tutorial 12.2: purchasing
    ("match_status",
     "-- Tutorial 12.2, test P1: three-way match by purchase order line\n"
     "-- Population: all PO lines; expected: no exception statuses",
     "WITH Received AS (\n"
     "    SELECT POLineID, SUM(QuantityReceived) AS QtyReceived\n"
     "    FROM GoodsReceiptLine\n"
     "    GROUP BY POLineID\n"
     "),\n"
     "Invoiced AS (\n"
     "    SELECT POLineID, SUM(Quantity) AS QtyInvoiced\n"
     "    FROM PurchaseInvoiceLine\n"
     "    WHERE POLineID IS NOT NULL\n"
     "    GROUP BY POLineID\n"
     "),\n"
     "Matched AS (\n"
     "    SELECT pol.POLineID, pol.Quantity AS QtyOrdered,\n"
     "        COALESCE(r.QtyReceived, 0) AS QtyReceived,\n"
     "        COALESCE(i.QtyInvoiced, 0) AS QtyInvoiced\n"
     "    FROM PurchaseOrderLine AS pol\n"
     "        LEFT JOIN Received AS r ON r.POLineID = pol.POLineID\n"
     "        LEFT JOIN Invoiced AS i ON i.POLineID = pol.POLineID\n"
     ")\n"
     "SELECT\n"
     "    CASE\n"
     "        WHEN QtyInvoiced > QtyReceived + 0.0001\n"
     "            THEN 'Exception: invoiced above received'\n"
     "        WHEN QtyReceived > QtyOrdered + 0.0001\n"
     "            THEN 'Exception: received above ordered'\n"
     "        WHEN QtyReceived = 0 THEN 'Not yet received'\n"
     "        WHEN QtyInvoiced < QtyReceived - 0.0001\n"
     "            THEN 'Received, not fully invoiced'\n"
     "        WHEN QtyReceived < QtyOrdered - 0.0001 THEN 'Partly received'\n"
     "        ELSE 'Matched'\n"
     "    END AS MatchStatus,\n"
     "    COUNT(*) AS POLines\n"
     "FROM Matched\n"
     "GROUP BY MatchStatus\n"
     "ORDER BY POLines DESC;"),
    ("price_tolerance",
     "-- Tutorial 12.2, test P2: invoice prices against order prices\n"
     "-- Population: invoice lines with a PO line; expected: none above 3%",
     "SELECT COUNT(*) AS InvoiceLines,\n"
     "    SUM(CASE WHEN ABS(pil.UnitCost - pol.UnitCost) / pol.UnitCost\n"
     "        > 0.03 THEN 1 ELSE 0 END) AS AboveThreePercent,\n"
     "    SUM(CASE WHEN ABS(pil.UnitCost - pol.UnitCost) / pol.UnitCost\n"
     "        > 0.02 THEN 1 ELSE 0 END) AS AboveTwoPercent,\n"
     "    ROUND(MAX((pil.UnitCost - pol.UnitCost) / pol.UnitCost), 4)\n"
     "        AS LargestIncrease,\n"
     "    ROUND(MIN((pil.UnitCost - pol.UnitCost) / pol.UnitCost), 4)\n"
     "        AS LargestDecrease\n"
     "FROM PurchaseInvoiceLine AS pil\n"
     "    INNER JOIN PurchaseOrderLine AS pol ON pol.POLineID = pil.POLineID;"),
    ("grni",
     "-- Tutorial 12.2, test P3: receipts not invoiced against account 2020\n"
     "-- Population: open receipt lines; expected: equal to the ledger",
     "WITH InvoicedByReceipt AS (\n"
     "    SELECT GoodsReceiptLineID, SUM(Quantity) AS QtyInvoiced\n"
     "    FROM PurchaseInvoiceLine\n"
     "    GROUP BY GoodsReceiptLineID\n"
     ")\n"
     "SELECT\n"
     "    (SELECT ROUND(SUM(grl.ExtendedStandardCost\n"
     "        * (1 - COALESCE(ibr.QtyInvoiced, 0) / grl.QuantityReceived)), 2)\n"
     "     FROM GoodsReceiptLine AS grl\n"
     "        LEFT JOIN InvoicedByReceipt AS ibr\n"
     "            ON ibr.GoodsReceiptLineID = grl.GoodsReceiptLineID\n"
     "     WHERE COALESCE(ibr.QtyInvoiced, 0) < grl.QuantityReceived - 0.0001)\n"
     "        AS NotInvoicedValue,\n"
     "    (SELECT ROUND(SUM(gl.Credit) - SUM(gl.Debit), 2)\n"
     "     FROM GLEntry AS gl\n"
     "        INNER JOIN Account AS a ON a.AccountID = gl.AccountID\n"
     "     WHERE a.AccountNumber = 2020 AND gl.PostingDate <= '2026-12-31')\n"
     "        AS LedgerBalance;"),
    ("approval_summary",
     "-- Tutorial 12.2, test P4: purchase order approvals\n"
     "-- Population: all purchase orders; expected: no rows",
     _APPROVAL_CTE + "\n"
     "SELECT Test, COUNT(*) AS Orders, ROUND(SUM(OrderTotal), 2) AS OrderValue\n"
     "FROM ApprovalExceptions\n"
     "GROUP BY Test\n"
     "ORDER BY Orders DESC;"),
    ("approval_detail",
     "-- Tutorial 12.2, test P5: the orders behind the approval exceptions\n"
     "-- Population: the orders flagged by test P4",
     _APPROVAL_CTE + ",\n"
     "Flagged AS (\n"
     "    SELECT PONumber, GROUP_CONCAT(Test, '; ') AS Tests\n"
     "    FROM ApprovalExceptions\n"
     "    GROUP BY PONumber\n"
     ")\n"
     "SELECT f.PONumber, po.OrderDate, po.OrderTotal,\n"
     "    c.JobTitle AS CreatedBy, a.JobTitle AS ApprovedBy,\n"
     "    a.MaxApprovalAmount, a.TerminationDate, f.Tests\n"
     "FROM Flagged AS f\n"
     "    INNER JOIN PurchaseOrder AS po ON po.PONumber = f.PONumber\n"
     "    INNER JOIN Employee AS c ON c.EmployeeID = po.CreatedByEmployeeID\n"
     "    INNER JOIN Employee AS a ON a.EmployeeID = po.ApprovedByEmployeeID\n"
     "ORDER BY po.OrderTotal DESC;"),
    ("approvers",
     "-- Tutorial 12.2, test P6: who approves the purchase orders\n"
     "-- Population: all purchase orders; expected: approval shared",
     "SELECT e.EmployeeID, e.JobTitle, COUNT(*) AS OrdersApproved\n"
     "FROM PurchaseOrder AS po\n"
     "    INNER JOIN Employee AS e ON e.EmployeeID = po.ApprovedByEmployeeID\n"
     "GROUP BY e.EmployeeID, e.JobTitle\n"
     "ORDER BY OrdersApproved DESC;"),
    # Tutorial 12.3: the hours and the pay
    ("time_profile",
     "-- Tutorial 12.3, test H1: a profile of the time clock entries\n"
     "-- Population: all clock entries; expected: approved and complete",
     "SELECT COUNT(*) AS Entries,\n"
     "    SUM(CASE WHEN ClockStatus <> 'Approved' THEN 1 ELSE 0 END)\n"
     "        AS NotApproved,\n"
     "    COUNT(*) - COUNT(ClockOutTime) AS NoClockOut,\n"
     "    COUNT(DISTINCT EmployeeID) AS Employees,\n"
     "    MIN(WorkDate) AS FirstWorkDate, MAX(WorkDate) AS LastWorkDate\n"
     "FROM TimeClockEntry;"),
    ("hours_chain",
     "-- Tutorial 12.3, test H2: clocked, recorded, and paid hours\n"
     "-- Population: every pay period; expected: equal in every period",
     "WITH Clocked AS (\n"
     "    SELECT PayrollPeriodID, SUM(RegularHours + OvertimeHours) AS Hours\n"
     "    FROM TimeClockEntry\n"
     "    GROUP BY PayrollPeriodID\n"
     "),\n"
     "Recorded AS (\n"
     "    SELECT PayrollPeriodID, SUM(RegularHours + OvertimeHours) AS Hours\n"
     "    FROM LaborTimeEntry\n"
     "    GROUP BY PayrollPeriodID\n"
     "),\n"
     "Paid AS (\n"
     "    SELECT pr.PayrollPeriodID, SUM(prl.Hours) AS Hours\n"
     "    FROM PayrollRegisterLine AS prl\n"
     "        INNER JOIN PayrollRegister AS pr\n"
     "            ON pr.PayrollRegisterID = prl.PayrollRegisterID\n"
     "    WHERE prl.LineType IN ('Regular Earnings', 'Overtime Earnings')\n"
     "    GROUP BY pr.PayrollPeriodID\n"
     ")\n"
     "SELECT COUNT(*) AS Periods,\n"
     "    SUM(CASE WHEN ABS(c.Hours - r.Hours) > 0.001\n"
     "        OR ABS(r.Hours - p.Hours) > 0.001 THEN 1 ELSE 0 END)\n"
     "        AS PeriodsThatDiffer,\n"
     "    ROUND(SUM(c.Hours), 1) AS Clocked,\n"
     "    ROUND(SUM(r.Hours), 1) AS Recorded,\n"
     "    ROUND(SUM(p.Hours), 1) AS Paid\n"
     "FROM Clocked AS c\n"
     "    INNER JOIN Recorded AS r ON r.PayrollPeriodID = c.PayrollPeriodID\n"
     "    INNER JOIN Paid AS p ON p.PayrollPeriodID = c.PayrollPeriodID;"),
    ("chain_2024",
     "-- Tutorial 12.3, test H3: the manufacturing hours of 2024 by kind\n"
     "-- Population: manufacturing labor time; expected: every period recorded",
     "SELECT pp.PeriodNumber, pp.PeriodStartDate,\n"
     "    ROUND(SUM(lt.RegularHours + lt.OvertimeHours), 0) AS Hours,\n"
     "    ROUND(SUM(CASE lt.LaborType WHEN 'Direct Manufacturing'\n"
     "        THEN lt.RegularHours + lt.OvertimeHours ELSE 0 END), 0)\n"
     "        AS DirectHours,\n"
     "    ROUND(SUM(CASE lt.LaborType WHEN 'Indirect Manufacturing'\n"
     "        THEN lt.RegularHours + lt.OvertimeHours ELSE 0 END), 0)\n"
     "        AS IndirectHours\n"
     "FROM LaborTimeEntry AS lt\n"
     "    INNER JOIN PayrollPeriod AS pp\n"
     "        ON pp.PayrollPeriodID = lt.PayrollPeriodID\n"
     "WHERE lt.LaborType <> 'NonManufacturing' AND pp.FiscalYear = 2024\n"
     "GROUP BY pp.PayrollPeriodID, pp.PeriodNumber, pp.PeriodStartDate\n"
     "ORDER BY pp.PeriodStartDate;"),
    ("chain_exceptions",
     "-- Tutorial 12.3, test H4: time paid to another person or unapproved\n"
     "-- Population: all earnings lines; expected: no rows",
     "SELECT 'Time paid to another employee' AS Test,\n"
     "    pr.EmployeeID AS PaidID, pe.JobTitle AS PaidTitle,\n"
     "    lt.EmployeeID AS WorkedID, we.JobTitle AS WorkedTitle,\n"
     "    we.TerminationDate AS WorkerLeft, prl.Amount\n"
     + _EARNINGS +
     "WHERE lt.EmployeeID <> pr.EmployeeID\n"
     "UNION ALL\n"
     "SELECT 'Time paid on an unapproved clock entry',\n"
     "    pr.EmployeeID, pe.JobTitle, lt.EmployeeID, we.JobTitle,\n"
     "    we.TerminationDate, prl.Amount\n"
     + _EARNINGS +
     "    INNER JOIN TimeClockEntry AS tc\n"
     "        ON tc.TimeClockEntryID = lt.TimeClockEntryID\n"
     "WHERE tc.ClockStatus <> 'Approved';"),
    ("pay_expectation",
     "-- Tutorial 12.3, test H5: earnings paid against hours and pay rates\n"
     "-- Population: hourly earnings lines; expected: within a cent a line",
     "WITH Expected AS (\n"
     "    SELECT pp.FiscalYear, prl.Amount,\n"
     "        prl.Hours * e.BaseHourlyRate\n"
     "            * CASE prl.LineType WHEN 'Overtime Earnings'\n"
     "                THEN 1.5 ELSE 1 END AS ExpectedAmount\n"
     "    FROM PayrollRegisterLine AS prl\n"
     "        INNER JOIN PayrollRegister AS pr\n"
     "            ON pr.PayrollRegisterID = prl.PayrollRegisterID\n"
     "        INNER JOIN PayrollPeriod AS pp\n"
     "            ON pp.PayrollPeriodID = pr.PayrollPeriodID\n"
     "        INNER JOIN Employee AS e ON e.EmployeeID = pr.EmployeeID\n"
     "    WHERE prl.LineType IN ('Regular Earnings', 'Overtime Earnings')\n"
     ")\n"
     "SELECT FiscalYear, ROUND(SUM(Amount), 2) AS EarningsPaid,\n"
     "    ROUND(SUM(ExpectedAmount), 2) AS Expected,\n"
     "    ROUND(SUM(Amount) - SUM(ExpectedAmount), 2) AS Difference,\n"
     "    SUM(CASE WHEN ABS(Amount - ExpectedAmount) > 0.01 THEN 1 ELSE 0 END)\n"
     "        AS LinesAboveOneCent\n"
     "FROM Expected\n"
     "GROUP BY FiscalYear\n"
     "ORDER BY FiscalYear;"),
    ("overtime_length",
     "-- Tutorial 12.3, test H6: overtime and its approvals\n"
     "-- Population: clock entries with overtime; expected: approved",
     "SELECT\n"
     "    CASE WHEN OvertimeHours <= 0.5 THEN 'Half an hour or less'\n"
     "        ELSE 'More than half an hour' END AS OvertimeLength,\n"
     "    COUNT(*) AS Entries,\n"
     "    SUM(CASE WHEN OvertimeApprovalID IS NULL THEN 1 ELSE 0 END)\n"
     "        AS WithoutApproval,\n"
     "    ROUND(SUM(OvertimeHours), 1) AS OvertimeHours\n"
     "FROM TimeClockEntry\n"
     "WHERE OvertimeHours > 0\n"
     "GROUP BY OvertimeLength;"),
    ("overtime_unapproved",
     "-- Tutorial 12.3, test H7: long overtime without an approval\n"
     "-- Population: overtime above half an hour; expected: no rows",
     "SELECT e.JobTitle, e.TerminationDate, tc.WorkDate,\n"
     "    tc.OvertimeHours, tc.ClockOutTime, tc.ClockStatus,\n"
     "    oa.OvertimeApprovalID AS UnlinkedApproval,\n"
     "    ap.JobTitle AS ApprovedBy\n"
     "FROM TimeClockEntry AS tc\n"
     "    INNER JOIN Employee AS e ON e.EmployeeID = tc.EmployeeID\n"
     "    LEFT JOIN OvertimeApproval AS oa\n"
     "        ON oa.EmployeeID = tc.EmployeeID AND oa.WorkDate = tc.WorkDate\n"
     "    LEFT JOIN Employee AS ap ON ap.EmployeeID = oa.ApprovedByEmployeeID\n"
     "WHERE tc.OvertimeHours > 0.5 AND tc.OvertimeApprovalID IS NULL;"),
    ("surge_days",
     "-- Tutorial 12.3, test H8: days when everyone clocked the same hours\n"
     "-- Population: manufacturing clock entries; expected: no such days",
     "WITH PlantDays AS (\n"
     "    SELECT tc.WorkDate, COUNT(*) AS Employees,\n"
     "        COUNT(DISTINCT tc.RegularHours + tc.OvertimeHours)\n"
     "            AS HourPatterns,\n"
     "        SUM(tc.OvertimeHours) AS OvertimeHours\n"
     + _PLANT_DAYS +
     ")\n"
     "SELECT strftime('%Y', WorkDate) AS WorkYear,\n"
     "    SUM(CASE WHEN HourPatterns = 1 AND Employees > 1\n"
     "        THEN 1 ELSE 0 END) AS SurgeDays,\n"
     "    MAX(CASE WHEN HourPatterns = 1 AND Employees > 1\n"
     "        THEN Employees END) AS EmployeesPerDay,\n"
     "    ROUND(SUM(CASE WHEN HourPatterns = 1 AND Employees > 1\n"
     "        THEN OvertimeHours ELSE 0 END), 0) AS SurgeOvertime,\n"
     "    ROUND(SUM(CASE WHEN HourPatterns = 1 AND Employees > 1\n"
     "        THEN OvertimeHours ELSE 0 END) / SUM(OvertimeHours), 3)\n"
     "        AS SurgeShare\n"
     "FROM PlantDays\n"
     "GROUP BY WorkYear\n"
     "ORDER BY WorkYear;"),
    ("late_by_year",
     "-- Tutorial 12.3, test H9: direct time recorded after its operation\n"
     "-- Population: direct labor time; expected: a small share",
     "WITH SurgeDays AS (\n"
     "    SELECT tc.WorkDate\n"
     + _PLANT_DAYS +
     "    HAVING COUNT(DISTINCT tc.RegularHours + tc.OvertimeHours) = 1\n"
     "        AND COUNT(*) > 1\n"
     ")\n"
     "SELECT strftime('%Y', lt.WorkDate) AS WorkYear,\n"
     "    ROUND(SUM(lt.RegularHours + lt.OvertimeHours), 0) AS DirectHours,\n"
     f"    ROUND(SUM({_AFTER_END}), 0)\n"
     "        AS AfterEnd,\n"
     f"    ROUND(SUM({_AFTER_END})\n"
     "        / SUM(lt.RegularHours + lt.OvertimeHours), 3) AS ShareAfterEnd,\n"
     "    ROUND(SUM(CASE WHEN lt.WorkDate > op.ActualEndDate\n"
     "        AND sd.WorkDate IS NOT NULL\n"
     "        THEN lt.RegularHours + lt.OvertimeHours ELSE 0 END), 0)\n"
     "        AS AfterEndOnSurgeDays\n"
     "FROM LaborTimeEntry AS lt\n"
     "    INNER JOIN WorkOrderOperation AS op\n"
     "        ON op.WorkOrderOperationID = lt.WorkOrderOperationID\n"
     "    LEFT JOIN SurgeDays AS sd ON sd.WorkDate = lt.WorkDate\n"
     "WHERE lt.LaborType = 'Direct Manufacturing'\n"
     "GROUP BY WorkYear\n"
     "ORDER BY WorkYear;"),
    ("late_by_center",
     "-- Tutorial 12.3, test H10: late direct time by work center, 2026\n"
     "-- Population: direct labor time of 2026; expected: a small share",
     "SELECT wc.WorkCenterName,\n"
     "    ROUND(SUM(lt.RegularHours + lt.OvertimeHours), 0) AS DirectHours,\n"
     f"    ROUND(SUM({_AFTER_END})\n"
     "        / SUM(lt.RegularHours + lt.OvertimeHours), 3) AS ShareAfterEnd\n"
     "FROM LaborTimeEntry AS lt\n"
     "    INNER JOIN WorkOrderOperation AS op\n"
     "        ON op.WorkOrderOperationID = lt.WorkOrderOperationID\n"
     "    INNER JOIN WorkCenter AS wc ON wc.WorkCenterID = op.WorkCenterID\n"
     "WHERE lt.LaborType = 'Direct Manufacturing'\n"
     "    AND lt.WorkDate BETWEEN '2026-01-01' AND '2026-12-31'\n"
     "GROUP BY wc.WorkCenterID, wc.WorkCenterName\n"
     "ORDER BY ShareAfterEnd DESC;"),
]
