table Employee

	column EmployeeID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: EmployeeID

	column EmployeeName
		dataType: string
		summarizeBy: none
		sourceColumn: EmployeeName

	column JobTitle
		dataType: string
		summarizeBy: none
		sourceColumn: JobTitle

	column PayClass
		dataType: string
		summarizeBy: none
		sourceColumn: PayClass

	partition Employee = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T74_Employee",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"EmployeeID", "EmployeeName", "JobTitle", "PayClass"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"EmployeeID", Int64.Type}, {"EmployeeName", type text},
			        {"JobTitle", type text}, {"PayClass", type text}})
			in
			    Typed

