table ProductionCompletionLine

	column ProductionCompletionLineID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ProductionCompletionLineID

	column ProductionCompletionID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ProductionCompletionID

	column ItemID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ItemID

	column QuantityCompleted
		dataType: double
		summarizeBy: sum
		sourceColumn: QuantityCompleted

	column CompletionDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: CompletionDate

	partition ProductionCompletionLine = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T57_ProductionCompletionLine",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"ProductionCompletionLineID", "ProductionCompletionID", "ItemID", "QuantityCompleted"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"ProductionCompletionLineID", Int64.Type}, {"ProductionCompletionID", Int64.Type},
			        {"ItemID", Int64.Type}, {"QuantityCompleted", type number}}),
			    Merged = Table.NestedJoin(Typed, {"ProductionCompletionID"}, Completions, {"ProductionCompletionID"}, "H", JoinKind.LeftOuter),
			    Expanded = Table.ExpandTableColumn(Merged, "H", {"CompletionDate"})
			in
			    Expanded

