table SalesInvoiceLine

	/// Invoiced revenue: the sum of LineTotal.
	measure Revenue = SUM ( SalesInvoiceLine[LineTotal] )
		formatString: #,0.00

	measure 'List Amount' = SUM ( SalesInvoiceLine[ListAmount] )
		formatString: #,0.00

	measure Discounts = SUM ( SalesInvoiceLine[DiscountAmount] )
		formatString: #,0.00

	measure 'Price Before Discount' = SUMX ( SalesInvoiceLine, SalesInvoiceLine[Quantity] * SalesInvoiceLine[UnitPrice] )
		formatString: #,0.00

	measure 'Discount Rate' = DIVIDE ( [Discounts], [Price Before Discount] )
		formatString: 0.00%

	measure 'Average of Discount' = AVERAGE ( SalesInvoiceLine[Discount] )
		formatString: 0.00%

	measure Invoices = DISTINCTCOUNT ( SalesInvoiceLine[SalesInvoiceID] )
		formatString: #,0

	measure 'Invoice Lines' = COUNTROWS ( SalesInvoiceLine )
		formatString: #,0

	measure 'Standard Cost' =
			SUMX (
			    SalesInvoiceLine,
			    SalesInvoiceLine[Quantity] * RELATED ( 'Item'[StandardCost] )
			)
		formatString: #,0.00

	measure 'Gross Margin' = [Revenue] - [Standard Cost]
		formatString: #,0.00

	measure 'Margin %' =
			VAR Rev = [Revenue]
			RETURN
			    DIVIDE ( Rev - [Standard Cost], Rev )
		formatString: 0.00%

	measure 'Furniture Revenue' = CALCULATE ( [Revenue], 'Item'[ItemGroup] = "Furniture" )
		formatString: #,0.00

	measure 'Share of Revenue' = DIVIDE ( [Revenue], CALCULATE ( [Revenue], REMOVEFILTERS ( 'Item' ) ) )
		formatString: 0.00%

	measure 'Share with ALL' = DIVIDE ( [Revenue], CALCULATE ( [Revenue], ALL ( SalesInvoiceLine ) ) )
		formatString: 0.00%

	measure 'Revenue PY' = CALCULATE ( [Revenue], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
		formatString: #,0.00

	measure 'Revenue YoY %' = DIVIDE ( [Revenue] - [Revenue PY], [Revenue PY] )
		formatString: 0.00%

	measure 'Revenue YTD' = TOTALYTD ( [Revenue], 'Date'[Date] )
		formatString: #,0.00

	measure 'Margin % PY' = CALCULATE ( [Margin %], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
		formatString: 0.00%

	measure 'Revenue by Ship Date' = CALCULATE ( [Revenue], USERELATIONSHIP ( SalesInvoiceLine[ShipmentDate], 'Date'[Date] ) )
		formatString: #,0.00

	column SalesInvoiceLineID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: SalesInvoiceLineID

	column SalesInvoiceID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: SalesInvoiceID

	column ItemID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ItemID

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantity

	column BaseListPrice
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BaseListPrice

	column UnitPrice
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: UnitPrice

	column Discount
		dataType: double
		summarizeBy: none
		sourceColumn: Discount

	column LineTotal
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: LineTotal

	column PromotionID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: PromotionID

	column ShipmentLineID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ShipmentLineID

	column PricingMethod
		dataType: string
		summarizeBy: none
		sourceColumn: PricingMethod

	column ListAmount
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: ListAmount

	column DiscountAmount
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: DiscountAmount

	column InvoiceNumber
		dataType: string
		summarizeBy: none
		sourceColumn: InvoiceNumber

	column InvoiceDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: InvoiceDate

	column CustomerID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: CustomerID

	column ShipmentDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: ShipmentDate

	partition SalesInvoiceLine = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T17_SalesInvoiceLine",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"SalesInvoiceLineID", "SalesInvoiceID", "ItemID", "Quantity", "BaseListPrice",
			        "UnitPrice", "Discount", "LineTotal", "PromotionID", "ShipmentLineID", "PricingMethod"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"SalesInvoiceLineID", Int64.Type}, {"SalesInvoiceID", Int64.Type},
			        {"ItemID", Int64.Type}, {"Quantity", type number}, {"BaseListPrice", type number}, {"UnitPrice", type number},
			        {"Discount", type number}, {"LineTotal", type number}, {"PromotionID", Int64.Type}, {"ShipmentLineID", Int64.Type},
			        {"PricingMethod", type text}}),
			    ListAmount = Table.AddColumn(Typed, "ListAmount", each [Quantity] * [BaseListPrice], type number),
			    DiscountAmount = Table.AddColumn(ListAmount, "DiscountAmount", each [Quantity] * [UnitPrice] * [Discount], type number),
			    Merged = Table.NestedJoin(DiscountAmount, {"SalesInvoiceID"}, SalesInvoice, {"SalesInvoiceID"}, "Header", JoinKind.LeftOuter),
			    Expanded = Table.ExpandTableColumn(Merged, "Header", {"InvoiceNumber", "InvoiceDate", "CustomerID"}),
			    Shipped = Table.NestedJoin(Expanded, {"ShipmentLineID"}, ShipDates, {"ShipmentLineID"}, "Ship", JoinKind.LeftOuter),
			    WithShip = Table.ExpandTableColumn(Shipped, "Ship", {"ShipmentDate"})
			in
			    WithShip

