table Account

	column AccountID
		dataType: int64
		summarizeBy: none
		sourceColumn: AccountID

	column AccountNumber
		dataType: int64
		summarizeBy: none
		sourceColumn: AccountNumber

	column AccountName
		dataType: string
		summarizeBy: none
		sourceColumn: AccountName

	column AccountType
		dataType: string
		summarizeBy: none
		sourceColumn: AccountType

	column AccountSubType
		dataType: string
		summarizeBy: none
		sourceColumn: AccountSubType

	column Step
		dataType: string
		summarizeBy: none
		sourceColumn: Step

	column Activity
		dataType: string
		summarizeBy: none
		sourceColumn: Activity

	partition Account = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T1_Account",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"AccountID", "AccountNumber", "AccountName", "AccountType", "AccountSubType"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"AccountID", Int64.Type}, {"AccountNumber", Int64.Type}, {"AccountName", type text},
			        {"AccountType", type text}, {"AccountSubType", type text}}),
			    Step = Table.AddColumn(Typed, "Step", each if [AccountNumber] = 1010 then "Cash"
			        else if [AccountType] = "Revenue" or [AccountType] = "Expense" then "Net income"
			        else if [AccountSubType] = "Contra Fixed Asset" then "Depreciation"
			        else if [AccountNumber] = 1020 or [AccountNumber] = 1030 then "Receivables"
			        else if [AccountNumber] = 1040 or [AccountNumber] = 1045 or [AccountNumber] = 1046 then "Inventories"
			        else if [AccountSubType] = "Current Asset" or [AccountSubType] = "Contra Current Asset" then "Other current assets"
			        else if [AccountNumber] = 2010 or [AccountNumber] = 2020 then "Payables"
			        else if [AccountNumber] = 2050 then "Sales tax"
			        else if [AccountSubType] = "Current Liability" then "Other current liabilities"
			        else if [AccountSubType] = "Fixed Asset" or [AccountSubType] = "Noncurrent Asset" then "Fixed assets"
			        else "Debt and equity", type text),
			    Activity = Table.AddColumn(Step, "Activity", each if [Step] = "Cash" then "Cash" else if [Step] = "Fixed assets" then "Investing"
			        else if [Step] = "Debt and equity" then "Financing" else "Operating", type text)
			in
			    Activity

