table APInvoices

	column PurchaseInvoiceID
		dataType: int64
		summarizeBy: none
		sourceColumn: PurchaseInvoiceID

	column ReceivedDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: ReceivedDate

	column DueDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: DueDate

	column GrandTotal
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: GrandTotal

	column OpenBalance
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: OpenBalance

	partition APInvoices = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T37_PurchaseInvoice",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"PurchaseInvoiceID", "ReceivedDate", "DueDate", "GrandTotal"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"PurchaseInvoiceID", Int64.Type}, {"ReceivedDate", type date}, {"DueDate", type date}, {"GrandTotal", type number}}),
			    Dated = Table.SelectRows(Typed, each [ReceivedDate] <= #date(2026, 12, 31)),
			    M1 = Table.NestedJoin(Dated, {"PurchaseInvoiceID"}, APPaid, {"PurchaseInvoiceID"}, "P", JoinKind.LeftOuter),
			    E1 = Table.ExpandTableColumn(M1, "P", {"PaidTotal"}),
			    Open = Table.AddColumn(E1, "OpenBalance", each Number.Round([GrandTotal] - (if [PaidTotal] = null then 0 else [PaidTotal]), 2), type number),
			    Kept2 = Table.SelectRows(Table.RemoveColumns(Open, {"PaidTotal"}), each [OpenBalance] > 0)
			in
			    Kept2

