table ARInvoices

	column SalesInvoiceID
		dataType: int64
		summarizeBy: none
		sourceColumn: SalesInvoiceID

	column InvoiceDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: InvoiceDate

	column DueDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: DueDate

	column GrandTotal
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: GrandTotal

	column OpenBalance
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: OpenBalance

	partition ARInvoices = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T16_SalesInvoice",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"SalesInvoiceID", "InvoiceDate", "DueDate", "GrandTotal"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"SalesInvoiceID", Int64.Type}, {"InvoiceDate", type date}, {"DueDate", type date}, {"GrandTotal", type number}}),
			    Dated = Table.SelectRows(Typed, each [InvoiceDate] <= #date(2026, 12, 31)),
			    M1 = Table.NestedJoin(Dated, {"SalesInvoiceID"}, ARApplied, {"SalesInvoiceID"}, "A", JoinKind.LeftOuter),
			    E1 = Table.ExpandTableColumn(M1, "A", {"AppliedTotal"}),
			    M2 = Table.NestedJoin(E1, {"SalesInvoiceID"}, ARCredited, {"OriginalSalesInvoiceID"}, "C", JoinKind.LeftOuter),
			    E2 = Table.ExpandTableColumn(M2, "C", {"CreditedTotal"}),
			    Open = Table.AddColumn(E2, "OpenBalance", each Number.Round([GrandTotal] - (if [AppliedTotal] = null then 0 else [AppliedTotal])
			        - (if [CreditedTotal] = null then 0 else [CreditedTotal]), 2), type number),
			    Kept2 = Table.SelectRows(Table.RemoveColumns(Open, {"AppliedTotal", "CreditedTotal"}), each [OpenBalance] > 0)
			in
			    Kept2

