table DebtSchedule

	column DebtScheduleLineID
		dataType: int64
		summarizeBy: none
		sourceColumn: DebtScheduleLineID

	column DebtAgreementID
		dataType: int64
		summarizeBy: none
		sourceColumn: DebtAgreementID

	column PaymentDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: PaymentDate

	column PrincipalAmount
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: PrincipalAmount

	column InterestAmount
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: InterestAmount

	column EndingPrincipal
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: EndingPrincipal

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status

	partition DebtSchedule = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T43_DebtScheduleLine",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"DebtScheduleLineID", "DebtAgreementID", "PaymentDate", "PrincipalAmount", "InterestAmount", "EndingPrincipal", "Status"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"DebtScheduleLineID", Int64.Type}, {"DebtAgreementID", Int64.Type}, {"PaymentDate", type date},
			        {"PrincipalAmount", type number}, {"InterestAmount", type number}, {"EndingPrincipal", type number}, {"Status", type text}})
			in
			    Typed

