table Item

	column ItemID
		dataType: int64
		summarizeBy: none
		sourceColumn: ItemID

	column ItemCode
		dataType: string
		summarizeBy: none
		sourceColumn: ItemCode

	column ItemName
		dataType: string
		summarizeBy: none
		sourceColumn: ItemName

	column ItemGroup
		dataType: string
		summarizeBy: none
		sourceColumn: ItemGroup

	column TargetDaysSupply
		dataType: int64
		summarizeBy: none
		sourceColumn: TargetDaysSupply

	partition Item = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T44_Item",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"ItemID", "ItemCode", "ItemName", "ItemGroup"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"ItemID", Int64.Type}, {"ItemCode", type text}, {"ItemName", type text}, {"ItemGroup", type text}}),
			    Merged = Table.NestedJoin(Typed, {"ItemID"}, Targets, {"ItemID"}, "P", JoinKind.LeftOuter),
			    Expanded = Table.ExpandTableColumn(Merged, "P", {"TargetDaysSupply"})
			in
			    Expanded

