table CostCenter

	column CostCenterID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: CostCenterID

	column CostCenterName
		dataType: string
		summarizeBy: none
		sourceColumn: CostCenterName

	partition CostCenter = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T75_CostCenter",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"CostCenterID", "CostCenterName"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"CostCenterID", Int64.Type}, {"CostCenterName", type text}})
			in
			    Typed

