table Customer

	column CustomerID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: CustomerID

	column CustomerName
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerName

	column CustomerSegment
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerSegment

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

	partition Customer = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T4_Customer",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"CustomerID", "CustomerName", "CustomerSegment", "Region"}),
			    Typed = Table.TransformColumnTypes(Kept, {{"CustomerID", Int64.Type}, {"CustomerName", type text},
			        {"CustomerSegment", type text}, {"Region", type text}})
			in
			    Typed

