table Item

	column ItemID
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ItemID

	column ItemCode
		dataType: string
		summarizeBy: none
		sourceColumn: ItemCode

	column ItemName
		dataType: string
		summarizeBy: none
		sourceColumn: ItemName

	column ItemGroup
		dataType: string
		summarizeBy: none
		sourceColumn: ItemGroup

	column StandardCost
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: StandardCost

	column ListPrice
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: ListPrice

	column ProductType
		dataType: string
		summarizeBy: none
		sourceColumn: ProductType

	partition Item = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("D:\codes projects\Accounting_Analytics\datasets\CharlesRiver.xlsx"), null, true),
			    Data = Source{[Item="T44_Item",Kind="Table"]}[Data],
			    Kept = Table.SelectColumns(Data, {"ItemID", "ItemCode", "ItemName", "ItemGroup", "StandardCost", "ListPrice"}),
			    Sellable = Table.SelectRows(Kept, each [ListPrice] <> null),
			    WithType = Table.AddColumn(Sellable, "ProductType", each Text.Middle([ItemCode], 4, 3), type text),
			    Typed = Table.TransformColumnTypes(WithType, {{"ItemID", Int64.Type}, {"ItemCode", type text},
			        {"ItemName", type text}, {"ItemGroup", type text}, {"StandardCost", type number}, {"ListPrice", type number}})
			in
			    Typed

