{{< pagebreak >}}

## References

American Institute of Certified Public Accountants. (2020). *Audit evidence* (Statement on Auditing Standards No. 142). <https://www.aicpa-cima.com/resources/download/aicpa-statement-on-auditing-standards-no-142>

American Institute of Certified Public Accountants. (2026). *Guide to audit data analytics*. <https://www.aicpa-cima.com/cpe-learning/publication/guide-to-audit-data-analytics>

Azeroual, O., & Jha, M. (2021). Without data quality, there is no data migration. *Big Data and Cognitive Computing*, *5*(2), Article 24. <https://doi.org/10.3390/bdcc5020024>

Bochkay, K., Brown, S. V., Leone, A. J., & Tucker, J. W. (2023). Textual analysis in accounting: What's next? *Contemporary Accounting Research*, *40*(2), 765–805. <https://doi.org/10.1111/1911-3846.12825>

Cai, L., & Zhu, Y. (2015). The challenges of data quality and data quality assessment in the big data era. *Data Science Journal*, *14*, Article 2. <https://doi.org/10.5334/dsj-2015-002>

Cao, L., & Zhu, H. (2013). Normal accidents: Data quality problems in ERP-enabled manufacturing. *Journal of Data and Information Quality*, *4*(3), 1–26. <https://doi.org/10.1145/2458517.2458519>

Holmes, A. F., & Douglass, A. (2022). Artificial intelligence: Reshaping the accounting profession and the disruption to accounting education. *Journal of Emerging Technologies in Accounting*, *19*(1), 53–68. <https://doi.org/10.2308/JETA-2020-054>

Jans, M., Alles, M. G., & Vasarhelyi, M. A. (2014). A field study on the use of process mining of event logs as an analytical procedure in auditing. *The Accounting Review*, *89*(5), 1751–1773. <https://doi.org/10.2308/accr-50807>

{{< include /shared/fragments/_reference-wang-strong-1996.qmd >}}

{{< include /shared/fragments/_reference-wickham-2014.qmd >}}

Yan, Z., & Moffitt, K. C. (2019). Contract analytics in auditing. *Accounting Horizons*, *33*(3), 111–126. <https://doi.org/10.2308/acch-52457>
