"""Prepare the disposable slide inputs: the book index, each deck's metadata, the cited figures, the theme.

Everything written here is generated and gitignored (slides/_shared/, slides/_variables.yml and each
deck's slides/chapter-NN/_metadata.yml). Decks hold only their slides; the title, the footer, the
figures and the tables come from the book at every build.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import struct
import subprocess
import zlib
from pathlib import Path

from . import book_index
from .pptx_theme import theme_reference
from .verify import crop_key, cited_figures_in, load_manifest

PNG_SCALE = 2
# Slide classes that get a background in both formats: (fill, bar) token names.
BACKGROUNDS = {'divider': ('blue', 'amber'), 'in-practice': ('paper', 'teal'), 'watch-out': ('paper', 'coral'),
               'connecting-dots': ('paper', 'amber'), 'check': ('tint', 'blue'),
               'answer': ('tint', 'teal')}


def find_quarto() -> str:
    candidates = [os.environ.get('QUARTO_BIN'), shutil.which('quarto')]
    if os.name == 'nt':
        candidates += [str(Path(os.environ.get('LOCALAPPDATA', '')) / 'Programs/Quarto/bin/quarto.exe'),
                       r'C:\Program Files\Quarto\bin\quarto.exe']
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return str(candidate)
    raise RuntimeError('Quarto not found. Install the pinned version or set QUARTO_BIN.')


def reset_owned(root: Path, path: Path) -> None:
    """Only clear explicitly designated generated directories within this checkout."""
    resolved, base = path.resolve(), root.resolve()
    allowed = [base / 'slides/_shared', base / 'slides/_build', base / 'outputs/build']
    if not any(resolved == item or resolved.is_relative_to(item) for item in allowed):
        raise ValueError(f'Refusing to clear non-build directory: {resolved}')
    if path.is_symlink():
        raise ValueError(f'Refusing to clear symlink: {path}')
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)


def deck_ids(root: Path) -> list[str]:
    """Every deck that exists; a deck is published as soon as its source is there."""
    return sorted(path.parent.name for path in (root / 'slides').glob('chapter-[0-9][0-9]/index.qmd'))


def deck_metadata(index: dict, deck: str) -> dict:
    chapter = index['chapters'][deck]
    return {
        'title': f"Chapter {chapter['number']}: {chapter['title']}",
        'subtitle': index['book_title'],
        'book-chapter': deck,
        'format': {
            'revealjs': {'output-file': 'index.html',
                         'footer': f"Chapter {chapter['number']} · {chapter['title']}"},
            'pptx': {'output-file': f'{deck}.pptx', 'reference-doc': f'../_shared/theme/{deck}.pptx'},
        },
    }


def write_metadata(root: Path, index: dict, decks: list[str]) -> None:
    for path in (root / 'slides').glob('chapter-*/_metadata.yml'):
        if path.parent.name not in decks:
            path.unlink()
            if not any(path.parent.iterdir()):
                path.parent.rmdir()
    for deck in decks:
        if deck not in index['chapters']:
            raise ValueError(f'slides/{deck} has no matching chapter in the book')
        target = root / 'slides' / deck / '_metadata.yml'
        # JSON is valid YAML and keeps the generated file unambiguous.
        target.write_text('# Generated by scripts/slides/prepare.py from the book; do not edit.\n'
                          + json.dumps(deck_metadata(index, deck), indent=2, ensure_ascii=False) + '\n',
                          encoding='utf-8')


def cited_figures(root: Path, decks: list[str]) -> list[tuple[str, tuple | None]]:
    """Every (figure, crop) pair the decks cite, once each; crop is None for the whole figure."""
    found: list[tuple[str, tuple | None]] = []
    for deck in decks:
        for cited in cited_figures_in((root / 'slides' / deck / 'index.qmd').read_text(encoding='utf-8-sig')):
            if cited not in found:
                found.append(cited)
    return found


def crop_svg(source: Path, target: Path, crop: tuple) -> None:
    """The same drawing seen through a narrower window: the root viewBox, width and height shrink."""
    from scripts.export_drawio_svgs import parse_svg_length, replace_or_add_svg_attr
    text = source.read_text(encoding='utf-8')
    tag = re.search(r'<svg\b[^>]*>', text)
    if tag is None:
        raise ValueError(f'{source} has no <svg> element')
    root = tag.group(0)
    box = re.search(r'\sviewBox=(["\'])([^"\']+)\1', root)
    width = re.search(r'\swidth=(["\'])([^"\']+)\1', root)
    height = re.search(r'\sheight=(["\'])([^"\']+)\1', root)
    if not (box and width and height):
        raise ValueError(f'{source}: the <svg> element needs viewBox, width and height to be cropped')
    x, y, w, h = (float(value) for value in box.group(2).replace(',', ' ').split())
    (full_width, unit), (full_height, _) = parse_svg_length(width.group(2)), parse_svg_length(height.group(2))
    left, top, part_width, part_height = crop
    root = replace_or_add_svg_attr(root, 'viewBox', f'{x + left * w:g} {y + top * h:g} {part_width * w:g} {part_height * h:g}')
    root = replace_or_add_svg_attr(root, 'width', f'{part_width * full_width:g}{unit}')
    root = replace_or_add_svg_attr(root, 'height', f'{part_height * full_height:g}{unit}')
    # Draw.io sizes each label's foreignObject at 100% of the viewBox, from the origin. Under a narrower
    # viewBox that box no longer reaches a detail low in the figure, and the browser skips its labels,
    # so the crop pins it to the whole figure's size, which is what 100% meant before.
    body = re.sub(r'<foreignObject\b[^>]*>', lambda match: match.group(0)
                  .replace('width="100%"', f'width="{w:g}"').replace('height="100%"', f'height="{h:g}"'),
                  text[tag.end():])
    target.write_text(text[:tag.start()] + root + body, encoding='utf-8')


def crop_png(source: Path, target: Path, crop: tuple) -> None:
    from PIL import Image
    left, top, width, height = crop
    with Image.open(source) as image:
        box = (round(left * image.width), round(top * image.height),
               round((left + width) * image.width), round((top + height) * image.height))
        image.crop(box).save(target, optimize=True)


def figure_png(root: Path, source: Path, drawio_bin: Path | None) -> Path:
    """The PowerPoint copy of a Draw.io figure, exported once per version of its source."""
    from scripts import export_drawio_svgs as exporter
    cache = root / 'outputs/slide-png'
    target = cache / f'{source.stem}-{exporter.export_digest(source)[:12]}-s{PNG_SCALE}.png'
    if not target.is_file():
        for stale in cache.glob(f'{source.stem}-*.png'):
            stale.unlink()
        exporter.export_png(drawio_bin or exporter.find_drawio_executable(None), source, target, scale=PNG_SCALE)
    return target


def stage_figures(root: Path, index: dict, decks: list[str], stage: Path, *, png: bool,
                  drawio_bin: Path | None = None) -> None:
    target = stage / 'visuals'
    target.mkdir(parents=True, exist_ok=True)
    for identifier, crop in cited_figures(root, decks):
        figure = index['figures'].get(identifier)
        if figure is None:
            raise ValueError(f'No figure {identifier} in the book')
        source = root / figure['src'].lstrip('/')
        # A crop is staged under its own name, so a deck can show a figure whole and in detail.
        stem = source.stem + (f'.crop-{crop_key(crop)}' if crop else '')
        if crop and source.suffix.lower() == '.svg':
            crop_svg(source, target / f'{stem}.svg', crop)
        elif crop:
            crop_png(source, target / f'{stem}{source.suffix}', crop)
        else:
            shutil.copy2(source, target / source.name)
        if source.suffix.lower() == '.svg' and png:
            drawio = root / 'visuals/src' / f'{source.stem}.drawio'
            if not drawio.is_file():
                raise ValueError(f'{identifier}: no Draw.io source to export for PowerPoint ({drawio})')
            exported = figure_png(root, drawio, drawio_bin)
            if crop:
                crop_png(exported, target / f'{stem}.png', crop)
            else:
                shutil.copy2(exported, target / f'{stem}.png')


def solid_png(path: Path, width: int, height: int, fill: str, bar: str, bar_width: int) -> None:
    """A slide background: one color with a vertical bar at the left edge, as a minimal RGB PNG."""
    rgb = lambda value: bytes.fromhex(value)
    row = b'\x00' + rgb(bar) * bar_width + rgb(fill) * (width - bar_width)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))

    header = struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0)
    path.write_bytes(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', header)
                     + chunk(b'IDAT', zlib.compress(row * height, 9)) + chunk(b'IEND', b''))


def pandoc_reference(quarto: str, target: Path) -> Path:
    """Pandoc's own default PowerPoint template, the base every deck's template is themed from."""
    target.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([quarto, 'pandoc', '-o', str(target), '--print-default-data-file', 'reference.pptx'],
                   check=True)
    return target


def write_theme(root: Path, stage: Path, index: dict, decks: list[str], quarto: str | None) -> None:
    tokens = load_manifest(root / 'slides/theme/tokens.yml')
    colors, sizes = tokens['colors'], tokens['sizes']
    theme = stage / 'theme'
    theme.mkdir(parents=True, exist_ok=True)
    scss = '\n'.join(['/*-- scss:defaults --*/',
        f'$font-family-sans-serif: "{tokens["font"]}", "{tokens["fallback_font"]}", sans-serif;',
        f'$font-family-monospace: "{tokens["code_font"]}", monospace;',
        f'$body-color: #{colors["ink"]};', f'$body-bg: #{colors["paper"]};',
        f'$link-color: #{colors["blue"]};', f'$presentation-heading-color: #{colors["blue"]};',
        f'$presentation-font-size-root: {sizes["body"] * 4 / 3:g}px;',
        *(f'$aa-{name}: #{value};' for name, value in colors.items()),
        *(f'$aa-size-{name}: {value * 4 / 3:g}px;' for name, value in sizes.items()),
        '/*-- scss:rules --*/',
        f'.reveal h1 {{ font-size: {sizes["opening"] * 4 / 3:g}px; }}',
        f'.reveal h2 {{ font-size: {sizes["title"] * 4 / 3:g}px; }}', ''])
    (theme / 'tokens.scss').write_text(scss, encoding='utf-8')
    # Pandoc's PPTX code font is a document variable, not a master placeholder.
    (theme / 'metadata.yml').write_text(json.dumps({'monofont': tokens['code_font']}) + '\n', encoding='utf-8')
    for name, (fill, bar) in BACKGROUNDS.items():
        solid_png(theme / f'bg-{name}.png', 1600, 900, colors[fill], colors[bar], 20)
    if decks:
        base = pandoc_reference(quarto or find_quarto(), theme / 'pandoc-default.pptx')
        for deck in decks:
            chapter = index['chapters'][deck]
            theme_reference(base, theme / f'{deck}.pptx', tokens,
                            footer=f"Chapter {chapter['number']} · {chapter['title']}")


def prepare(root: Path, *, png: bool = True, drawio_bin: Path | None = None, quarto: str | None = None) -> dict:
    """Write every generated slide input; png=False skips the PowerPoint inputs (figure exports, templates)."""
    stage = root / 'slides/_shared'
    reset_owned(root, stage)
    index = book_index.write(root, stage / 'book.json')
    decks = deck_ids(root)
    write_metadata(root, index, decks)
    fragments = stage / 'fragments'
    fragments.mkdir()
    for fragment in sorted((root / 'shared/fragments').glob('*.qmd')):
        shutil.copy2(fragment, fragments / fragment.name)
    shutil.copy2(root / '_variables.yml', root / 'slides/_variables.yml')
    stage_figures(root, index, decks, stage, png=png, drawio_bin=drawio_bin)
    write_theme(root, stage, index, decks if png else [], quarto)
    return index
