{{< pagebreak >}}

## References

Caulkins, J. P., Morrison, E. L., & Weidemann, T. (2007). Spreadsheet errors and decision making. *Journal of Organizational and End User Computing*, *19*(3), 1–23. <https://doi.org/10.4018/joeuc.2007070101>

Church, K. S., Riley, J., & Schmidt, P. J. (2022). Has Excel become a "golden hammer": The paradox of data analytics in SME clusters. *Journal of Emerging Technologies in Accounting*, *19*(2), 211–234. <https://doi.org/10.2308/jeta-2020-051>

Janvrin, D., & Morrison, J. (2000). Using a structured design approach to reduce risks in end user spreadsheet development. *Information & Management*, *37*(1), 1–12. <https://doi.org/10.1016/S0378-7206(99)00029-4>

Panko, R. R. (1998). What we know about spreadsheet errors. *Journal of Organizational and End User Computing*, *10*(2), 15–21. <https://doi.org/10.4018/joeuc.1998040102>

Powell, S. G., Baker, K. R., & Lawson, B. (2008). A critical review of the literature on spreadsheet errors. *Decision Support Systems*, *46*(1), 128–138. <https://doi.org/10.1016/j.dss.2008.06.001>

{{< include /shared/fragments/_reference-powell-2009a.qmd >}}

Powell, S. G., Baker, K. R., & Lawson, B. (2009b). Impact of errors in operational spreadsheets. *Decision Support Systems*, *47*(2), 126–132. <https://doi.org/10.1016/j.dss.2009.02.002>

Public Company Accounting Oversight Board. (n.d.). *AS 1215: Audit documentation*. <https://pcaobus.org/oversight/standards/auditing-standards/details/AS1215>
